project:
  type: website
  output-dir: docs

editor:
  markdown:
    wrap: sentence

execute:
  freeze: auto

website:
  title: "Bayesian Regression: Theory & Practice"
  repo-url: https://github.com/michael-franke/Bayesian-Regression
  repo-actions: [edit, issue]
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Overview
      - section: "01: Basics"
        contents:
          - href: 01-basics.qmd
            text: Overview
          - href: practice-sheets/01a-wrangling-plotting.qmd
            text: Wrangling & plotting
          - href: practice-sheets/01b-simple-regression.qmd
            text: Simple linear regression
          - href: practice-sheets/01e-contrast-coding-tutorial.qmd
            text: Categorical predictors
          - href: practice-sheets/01c-priors.qmd
            text: Priors
          - href: practice-sheets/01d-predictives.qmd
            text: Predictions
          - href: practice-sheets/01f-catPreds-exercises.qmd
            text: "Exercises: Bayesian LMs"
          - href: practice-sheets/01g-cheat-sheet.qmd
            text: Cheat sheet
      - section: "02: Multi-level models"
        contents:
          - href: 02-hierarchical-models.qmd
            text: Overview
          - href: practice-sheets/02a-hierarchical-models-tutorial.qmd
            text: Hierarchical models (tutorial)
          - href: practice-sheets/02b-hierarchical-models-exercises.qmd
            text: Hierarchical models (exercises)
          - href: practice-sheets/02c-multi-membership.qmd
            text: Multi-membership
          - href: practice-sheets/02d-MLM-pooling.qmd
            text: MLMs & pooling
      - section: "03: GLMs & beyond"
        contents:
          - href: 03-GLM.qmd
            text: Overview
          - href: practice-sheets/03a-GLM-tutorial.qmd
            text: GLM (tutorial)
          - href: practice-sheets/03b-GLM-exercises.qmd
            text: GLM (exercises)
          - href: practice-sheets/03c-distributional-models.qmd
            text: Distributional models
          - href: practice-sheets/03d-mixture-models.qmd
            text: Mixture models
      - section: "04: MCMC sampling"
        contents:
          - href: 04-MCMC.qmd
            text: Overview
          - href: practice-sheets/04a-MCMC-diagnostics.qmd
            text: MCMC diagnostics
          - href: practice-sheets/04b-divergences.qmd
            text: Divergent transitions
      - section: "05: Model comparison"
        contents:
          - href: 05-model-comparison.qmd
            text: Overview
          - href: practice-sheets/05a-model-comparison.qmd
            text: Model comparison
      - section: "06: Causal inference"
        contents:
          - href: 06-causal-inference.qmd
            text: Overview
          - href: practice-sheets/06a-stochastic-dependence.qmd
            text: Stochastic dependence
          - href: practice-sheets/06b-causal-inference.qmd
            text: Causal inference
      - section: "07: Non-linear models"
        contents:
          - href: practice-sheets/07a-nonLinear.qmd
            text: Custom non-linearity
          - href: practice-sheets/07b-GAMs.qmd
            text: Generalized additive models
          - href: practice-sheets/07c-Gaussian-processes.qmd
            text: Gaussian processes regression

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: show
    code-summary: "Toggle code"
