project:
  type: website
  output-dir: docs

editor:
  markdown:
    wrap: sentence

execute:
  freeze: auto

website:
  title: "Bayesian Regression: Theory & Practice"
  repo-url: https://github.com/michael-franke/Bayesian-Regression
  repo-actions: [edit, issue]
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Overview
      - section: "00: Background"
        contents:
          - href: 00-background.qmd
            text: Overview
          - href: practice-sheets/00a-examples-WebPPL.qmd
            text: Thinking Bayesian
          - href: practice-sheets/00b-wrangling-plotting.qmd
            text: Wrangling & plotting
      - section: "01: Regression basics"
        contents:
          - href: 01-basics.qmd
            text: Overview
          - href: practice-sheets/01a-regression-WebPPL.qmd
            text: "Simple regr. in WebPPL"
          - href: practice-sheets/01b-regression-BRMS.qmd
            text: "Simple regr. in BRMS"
          - href: practice-sheets/01c-priors.qmd
            text: "Priors & predicitives"
      - section: "02: Categorical predictors"
        contents:
          - href: 02-categorical-predictors.qmd
            text: Overview
          - href: practice-sheets/02a-contrast-coding-tutorial.qmd
            text: Categorical predictors
          - href: practice-sheets/02b-catPreds-exercises.qmd
            text: "Exercises: Bayesian LMs"
      - section: "03: Multi-level models"
        contents:
          - href: 03-hierarchical-models.qmd
            text: Overview
          - href: practice-sheets/03a-hierarchical-models-tutorial.qmd
            text: Hierarchical models (tutorial)
          - href: practice-sheets/03b-hierarchical-models-exercises.qmd
            text: Hierarchical models (exercises)
          - href: practice-sheets/03c-multi-membership.qmd
            text: Multi-membership
          - href: practice-sheets/03d-MLM-pooling.qmd
            text: MLMs & pooling
      - section: "04: GLMs & beyond"
        contents:
          - href: 04-GLM.qmd
            text: Overview
          - href: practice-sheets/04a-GLM-tutorial.qmd
            text: GLM (tutorial)
          - href: practice-sheets/04b-GLM-exercises.qmd
            text: GLM (exercises)
          - href: practice-sheets/04c-GLM-predictives.qmd
            text: Predictions from GLMs
          - href: practice-sheets/04d-distributional-models.qmd
            text: Distributional models
          - href: practice-sheets/04e-mixture-models.qmd
            text: Mixture models
      - section: "05: MCMC sampling"
        contents:
          - href: 05-MCMC.qmd
            text: Overview
          - href: practice-sheets/05a-MCMC-diagnostics.qmd
            text: MCMC diagnostics
          - href: practice-sheets/05b-divergences.qmd
            text: Divergent transitions
      - section: "06: Model comparison"
        contents:
          - href: 06-model-comparison.qmd
            text: Overview
          - href: practice-sheets/06a-model-comparison.qmd
            text: Model comparison
      - section: "07: Model criticism"
        contents:
          - href: practice-sheets/07a-model-criticism.qmd
            text: Model criticism
      - section: "08: Causal inference"
        contents:
          - href: 08-causal-inference.qmd
            text: Overview
          - href: practice-sheets/08a-stochastic-dependence.qmd
            text: Stochastic dependence
          - href: practice-sheets/08b-causal-inference.qmd
            text: Causal inference
      - section: "09: Non-linear models"
        contents:
          - href: practice-sheets/09a-nonLinear.qmd
            text: Custom non-linearity
          - href: practice-sheets/09b-GAMs.qmd
            text: Generalized additive models
          - href: practice-sheets/09c-Gaussian-processes.qmd
            text: Gaussian processes regression
      - section: "10: Practical stuff"
        contents:
          - href: practice-sheets/10a-cheat-sheet.qmd
            text: BRMS cheat sheet

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: show
    code-summary: "Toggle code"
